### PR TITLE
Add report submission

### LINKED ISSUE #197: [Capstone] Add option to submit report 1 & 2 on portal
This would be a very good *good to have*. Currently, for the capstone, the students submit the app URL through the portal. For batch 5 we are thinking about asking students to submit the reports as PDF. It would be fantastic if we had two submit boxes, one for each report, timestamped when uploading to, what I assume, an s3 bucket. 

Setting priority as high due to this being a time-sensitive decision. Capstone kick off on the 17th of January. Report delivery on the following dates:
- Report 1 delivery on February 6th
- Report 1 resubmission up to March 6th
- Report 2 delivery on March 6th
- Report 2 resubmission up to March 20th

### PR DESCRIPTION
**Pull request by hcastilho**
Closes #197

### CODE REVIEW

**Review by cimendes — CHANGES_REQUESTED** [review]
Adding my struggles below, but TL; DR: I broke the thing..

**Comment by cimendes** [comment]
My dear @hcastilho, I am confused...  And I broke the thing. I don't know if this was your purpose, but if it was, great success! 

To test I wanted to submit a report in PDF as a student.

I've cloned the branch and launched the portal as explained [here](https://ldsa-portal.readthedocs.io/en/latest/install.html) . Loaded the test data and created a capstone in the admin portal.

These are the settings I used for testing purposes:
Screenshot 2022-01-12 at 19 55 52

Capstone was created as expected: (student view)
Screenshot 2022-01-12 at 19 57 41

Added the URL as a test, worked well, but the report section showed up as "Not accepting reports"
Screenshot 2022-01-12 at 19 58 43
 
 Noticed there was a Reports section on the admin panel, and thought that maybe I needed to create the report there (as if it was a unit). And I broke the app when I clicked it
Screenshot 2022-01-12 at 20 03 03

 Now.. Is this a _me_ problem or have a stumbled across an actual error? The due date was today at midnight. I expect the reports to start as open and close at the defined due date. 
 
Sorry Hugo 😄

**Comment by cimendes** [comment]
The actual error message when going to `http://localhost:8000/admin/capstone/report/add/`

`django.core.exceptions.FieldError: 'submited_at' cannot be specified for Report model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class ReportAdmin.`

**Comment by hcastilho** [comment]
00:00 on the 12th is in the past
days are from 00:00 till 23:59

The reports section in the backoffice is not supposed add reports (that is done by the students in the portal) so I didn't test it.

**Comment by cimendes** [comment]
Feeling slight stupid now...

set everything to be in the future for the non-time-travelers, submitted (and updated) report 1 successfully
image
Screenshot 2022-01-12 at 20 38 54

Is the submission of reports sequential? Do I need to close report 1 for report 1 resubmission to open up?

**Comment by cimendes** [comment]
How do I have access to the reports? The backend doesn't show me where they are stored
image

If I click on the `test_capstone` it breaks with `django.core.exceptions.FieldError: 'submited_at' cannot be specified for Report model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class ReportAdmin.`

**Comment by cimendes** [comment]
Can I make a request and Add the slackID to this table? We don't have an easy way to deliver the reports with comments to the students so having the id to click and open the conversation on slack would help a lot

**Comment by cimendes** [comment]
Resubmission of report 1 is concurrent with submission of report 2. I suggest opening and closing report submission for each instance on the back office.

**Review by cimendes — APPROVED** [review]

**Pull request merged**
