### PR TITLE
adding capstone scoring script with correct scoring function

### PR DESCRIPTION
**Pull request by buedaswag**
just added last year's script, using recall as a scoring function

### CODE REVIEW

**Review by hcastilho — COMMENTED** [review]
Shouldn't this live in the instructors repository or somewhere explicitly batch related?
Seems like the portal is no the right place for this to live.

**Comment by cimendes** [comment]
Can I suggest the capstone branch on the LDSSA instructor repo? 

https://github.com/LDSSA/batch5-instructors/tree/capstone-data-prep

**Comment by cimendes** [comment]
Here's the scoring function we used for hackathon 06

https://github.com/LDSSA/batch5-instructors/blob/main/S06%20-%20DS%20in%20the%20Real%20World/HCKT06%20-%20DS%20in%20the%20Real%20World/portal/score.py

**Comment by hcastilho** [comment]
Will be placed in the instructors repo/

**Pull request closed without merging**
